apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-configmap-access
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-role  # Role en el namespace 'default'
  apiGroup: rbac.authorization.k8s.io

